#!/bin/bash

echo "Adding Swap"
echo ""
echo ""
echo ""

# Adds 30GB of swap (virtual ram) via a swap file
sudo dd if=/dev/zero of=/root/myswapfile bs=1M count=30720
sudo chmod 600 /root/myswapfile
sudo mkswap /root/myswapfile
free -m
sudo swapon /root/myswapfile

# At the conclusion of running this file, a swap file 30GB large has been
# created and mounted to /root/myswapfile
