#!/bin/bash

# Adds 30GB of swap (virtual ram) via a swap file
sudo dd if=/dev/zero of=/root/myswapfile bs=1M count=30720
sudo chmod 600 /root/myswapfile
sudo mkswap /root/myswapfile
free -m

# At the conclusion of running this file, a swap file 30GB large has been
# created but the OS does not yet know it is a place to swap files to. It is
# expected that the command ./mount_drives is given following this to conclude
# swap setup
