#!/bin/bash

# Based on Ben's original script (https://stackoverflow.com/questions/29667330/automated-installation-of-r-studio-using-shell-script)

echo "Installing Programming Software"
echo ""
echo ""
echo ""


# Dependencies
while sudo fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1;
do
  echo "Waiting for lock"
  sleep 1
done
sudo apt-get -y install libopenblas-base  make gcc git pandoc unzip curl libssl-dev gdebi-core nfs-common

bash -c "export PKG_CONFIG_PATH=$(sudo find / -name 'openssl.pc')"

# Install R & RStudio
sudo bash -c 'sudo echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/" >> /etc/apt/sources.list'

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

while sudo fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1;
do
  echo "Waiting for lock"
  sleep 1
done
sudo apt-get -y update

while sudo fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1;
do
  echo "Waiting for lock"
  sleep 1
done
sudo apt-get -y install r-base r-base-dev libdbi1

# Download the installer to a temp file, install it, and remove the temp file
while sudo fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1;
do
  echo "Waiting for lock"
  sleep 1
done
Download_URL=https://s3.amazonaws.com/rstudio-dailybuilds/rstudio-server-1.1.463-amd64.deb
FILE=$(mktemp)
sudo wget "$Download_URL" -qO $FILE && sudo dpkg -i $FILE
sudo rm $FILE

# Install JupyterHub (https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server)

# curl -o ./Anaconda3.sh https://repo.anaconda.com/archive/Anaconda3-2018.12-Linux-x86_64.sh
# bash Anaconda3.sh -b
#
# sudo apt-get -y install python-pip python3-pip
# sudo apt-get -y install npm nodejs
# npm install -g configurable-http-proxy
# pip3 install jupyterhub
# pip3 install --upgrade notebook
