#!/bin/bash

# To be run after provision-time (requires interactive input)
sudo apt-get -y update
curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
sudo python ./awslogs-agent-setup.py --region us-west-2
