#!/bin/bash

echo "Mounting Drives"
echo ""
echo ""
echo ""

# Takes a single argument - data_folder_path - and mounts the EBS volume at /dev/nvme1n1 at the data_folder_path. data_folder_path defaults to /home/data if left unspecified

echo "${1=/home/data}"

#sudo mount /dev/xvdf $1
sudo mount /dev/nvme1n1 $1
sudo chmod 777 $1
sudo swapon /root/myswapfile
