#!/bin/bash

echo "Mounting Drives"
echo ""
echo ""
echo ""

# Takes a single argument - data_folder_path - and mounts the EBS volume at /dev/nvme1n1 at the data_folder_path. data_folder_path defaults to /home/data if left unspecified

path="${1:-/home/data}"

#sudo mount /dev/xvdf $path
sudo mount /dev/nvme1n1 $path
sudo chmod 777 $path
sudo swapon /root/myswapfile
